<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DummyKeluhanSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('dummy_keluhans')->insert([
            [
                'user_id' => 1,
                'judul' => 'Jalan Rusak di Kertajaya',
                'keluhan' => 'Jalan berlubang cukup besar dan membahayakan pengendara motor.',
                'konten' => 'Mohon dilakukan perbaikan jalan karena lubang cukup dalam dan sering menyebabkan pengendara menghindar mendadak.',
                'tanggal_keluhan' => '2026-07-01',
                'kecamatan_id' => 1,
                'kelurahan_id' => 1,
                'kategori_id' => 1,
                'topik_id' => 1,
                'instansi_id' => 1,
                'channel_id' => 1,
                'status_id' => 1,
                'latitude' => '-7.275600',
                'longitude' => '112.741100',
                'alamat' => 'Jl. Kertajaya, Gubeng, Surabaya',
                'sosial_media' => null,
                'jenis_kelamin' => 'Laki-laki',
                'nomor_telepon' => '081234567890',
                'nama' => 'Akhdan Sayudha',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'judul' => 'Sampah Menumpuk di Depan Gang',
                'keluhan' => 'Sampah rumah tangga menumpuk dan belum diangkut selama beberapa hari.',
                'konten' => 'Sampah mulai menimbulkan bau tidak sedap dan mengganggu warga sekitar.',
                'tanggal_keluhan' => '2026-07-02',
                'kecamatan_id' => 1,
                'kelurahan_id' => 2,
                'kategori_id' => 2,
                'topik_id' => 2,
                'instansi_id' => 2,
                'channel_id' => 1,
                'status_id' => 2,
                'latitude' => '-7.270900',
                'longitude' => '112.750200',
                'alamat' => 'Jl. Airlangga, Gubeng, Surabaya',
                'sosial_media' => null,
                'jenis_kelamin' => 'Laki-laki',
                'nomor_telepon' => '081234567891',
                'nama' => 'Farrel Mario',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'judul' => 'Lampu Jalan Mati di Rungkut',
                'keluhan' => 'Lampu penerangan jalan umum mati sejak minggu lalu.',
                'konten' => 'Area jalan menjadi gelap pada malam hari dan rawan membahayakan pengguna jalan.',
                'tanggal_keluhan' => '2026-07-03',
                'kecamatan_id' => 3,
                'kelurahan_id' => 5,
                'kategori_id' => 5,
                'topik_id' => 3,
                'instansi_id' => 3,
                'channel_id' => 3,
                'status_id' => 3,
                'latitude' => '-7.321500',
                'longitude' => '112.768300',
                'alamat' => 'Jl. Rungkut Kidul, Surabaya',
                'sosial_media' => '@andini_putri',
                'jenis_kelamin' => 'Perempuan',
                'nomor_telepon' => '081234567892',
                'nama' => 'Andini Putri',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'judul' => 'Banjir Setelah Hujan Deras',
                'keluhan' => 'Air menggenang cukup tinggi setelah hujan deras.',
                'konten' => 'Saluran air diduga tersumbat sehingga air tidak cepat surut.',
                'tanggal_keluhan' => '2026-07-04',
                'kecamatan_id' => 2,
                'kelurahan_id' => 3,
                'kategori_id' => 1,
                'topik_id' => 4,
                'instansi_id' => 1,
                'channel_id' => 2,
                'status_id' => 4,
                'latitude' => '-7.290700',
                'longitude' => '112.797000',
                'alamat' => 'Jl. Keputih, Sukolilo, Surabaya',
                'sosial_media' => null,
                'jenis_kelamin' => 'Laki-laki',
                'nomor_telepon' => '081234567893',
                'nama' => 'Budi Santoso',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'judul' => 'Gangguan Ketertiban Malam Hari',
                'keluhan' => 'Terdapat aktivitas bising pada malam hari yang mengganggu warga.',
                'konten' => 'Mohon dilakukan pengecekan karena suara bising berlangsung sampai larut malam.',
                'tanggal_keluhan' => '2026-07-05',
                'kecamatan_id' => 4,
                'kelurahan_id' => 7,
                'kategori_id' => 3,
                'topik_id' => 5,
                'instansi_id' => 4,
                'channel_id' => 5,
                'status_id' => 5,
                'latitude' => '-7.300100',
                'longitude' => '112.733900',
                'alamat' => 'Jl. Darmo, Wonokromo, Surabaya',
                'sosial_media' => null,
                'jenis_kelamin' => 'Perempuan',
                'nomor_telepon' => '081234567894',
                'nama' => 'Siti Aminah',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}